name: Upload to EC2

on:
  push:
    branches: [ main ]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build and push docker
      run: |
        docker build -t ${{ secrets.DOCKER_NAME }}/ruby_frontend .
        docker login -p ${{ secrets.DOCKER_PASSWORD }} -u ${{ secrets.DOCKERUSERNAME }}
        docker push ${{ secrets.DOCKER_NAME }}/ruby_frontend  
    - name: Deploy Docker to EC2
      run: |
        touch password.pem
        echo "${{ secrets.SECRET_KEY_PAIR }}" >> password.pem
        chmod 400 password.pem
        ssh -i password.pem -t -t -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_ADDRESS }} << 'EOF'
        docker rm -f ruby_backend
        docker rmi ${{ secrets.DOCKER_NAME }}/ruby_frontend
        docker pull ${{ secrets.DOCKER_NAME }}/ruby_frontend
        docker run -d -p 80:80 --network ruby_project joshet/ruby_front
        screen -d -m
        exit
        EOF

  
